version: '3.8'

services:
  mysql:
     image: mariadb:10.8.3
     command: --default-authentication-plugin=mysql_native_password
     environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: product
      MYSQL_PASSWORD: product
     volumes:
        - ./mysql:/var/lib/mysql

  product-php:
    container_name: product
    build:
      context: ./php
    volumes:
      - ../app:/var/www/html

  product-nginx:
    image: nginx:stable-alpine

    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


