version: '3.8'

services:

  mysql:
    ports:
      - '4306:3306'

  mysql2:
    ports:
      - '4307:3306'

  product-php:
    build:
      args:
        WWW_DATA_UID: 1000
        WWW_DATA_GID: 1000

  product-nginx:
    ports:
      - "8080:80"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9009:8080